### PR TITLE
fix: custom field inheritance

### LINKED ISSUE #8498: customField inheritance not working
### Shopware Version

6.6.5.0-6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

According to the documentation (https://docs.shopware.com/en/shopware-6-en/settings/custom-fields), there is an inheritance with the customFields. Values should apply to all languages if set in the default language. Since Shopware 6.6.5.0 this no longer seems to work. If I set a customField value in the default language, it is empty in the other languages

### Expected behaviour

 CustomField values should apply to all languages if set in the default language

### How to reproduce

Create a customField set with a text and a checkbox field for the products. Go to the customFIelds in a product, activate the checkbox and write some text in the text field (in default language). Now switch to another language in the admin

6.6.4.1
You see the same values as in the default language and can now make changes

6.6.5.0 - 6.6.10.3
All values are empty. No more inheritance of the values from the default language. Values could now be saved empty by mistake

### PR DESCRIPTION
**Pull request by jleifeld**
### 1. Why is this change necessary?

The fix from #15905 still left two issues on the product specifications page:

- a checkbox custom field showed an inheritance icon in the root language although inheritance was not possible there
- translated custom text and checkbox fields did not show inheritance UI in the fallback language context

### 2. What does this change do, exactly?

This change fixes custom-field inheritance handling in `sw-custom-field-set-renderer` for the product specifications page.

It ensures that:
- inheritance UI is hidden when inheritance is not available
- translated custom fields can inherit from the correct fallback language
- inherited Meteor fields receive the correct inherited value and disabled state
- regression coverage exists for the specifications page and renderer behavior

### 3. Describe each step to reproduce the issue or behaviour.

1. Open: product detail page
2. Check `Text example` and `Checkbox example` in **English**.
3. Switch the smart bar language to **Deutsch**.
4. Check the same fields again.

Before this change:
- **English:** the checkbox showed an inheritance icon although inheritance was not possible
- **Deutsch:** text and checkbox fields did not show inheritance UI although they should inherit

After this change:
- **English:** no inheritance UI is shown
- **Deutsch:** inheritance UI is shown correctly and inherited fields are disabled

**Proof video:** 

https://github.com/user-attachments/assets/645c9af1-0527-4a10-8467-3de3411d632d

### 4. Please link to the relevant issues (if any).

- relates #15905

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by fabianzintgraf-dx — APPROVED** [review]
Grob geprüft: Umfang, betroffene Komponenten und CI-Status sehen konsistent aus, keine offensichtlichen groben Schnitzer gefunden.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 1]
```diff
@@ -245,6 +312,58 @@ export default {
...
+                if (this.translatedInheritanceLoadKey !== loadKey) {
+                    return;
+                }
+
+                this.inheritedCustomFields = inheritedEntity?.customFields ?? null;
+            } catch (error) {
+                console.error(error);
+
+                if (this.translatedInheritanceLoadKey === loadKey) {
+                    this.inheritedCustomFields = null;
```
Comment (davidtraum) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Is it intentional that no retry happens after an error in this case?
If not, we could call `resetTranslatedInheritanceState` here as well.

**Review by davidtraum — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 1 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: No, that isn’t intentional. I’ll call `resetTranslatedInheritanceState()` in the `catch` branch and add a unit test to cover recovery after a transient failure.

[the remark this answers is not in the document]
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: I’ll reset the translated inheritance state in the `catch` branch as well so transient failures can recover, and I’ll add a unit test for the reject-then-retry case

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 2]
```diff
@@ -160,9 +162,24 @@ export default {
                 'sw-field',
             ];
         },
+
+        translatedInheritanceLanguageId() {
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: The computed property name doesn't make much sense to me. It implies that an ID is being translated, which isn't happening. I think a name like `parentLanguageId` already helps out a lot.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 3]
```diff
@@ -209,13 +228,61 @@ export default {
             this.customFields = this.entity.customFields;
         },
 
-        getInheritedCustomField(customFieldName) {
-            const value = this.parentEntity?.translated?.customFields?.[customFieldName] ?? null;
+        isTranslatedCustomFieldInheritanceContext() {
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: It's quite a verbose name. Suggestion: `usesTranslatedInheritance` as a computed property.
Although here's one more take:
This name suggests that the inheritance translates our fields into the correct language. But in my understanding, it shows the foreign language as a fallback. Maybe a term like `foreignLanguage`, `untranslated` or `indirect` would fit better

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 4]
```diff
@@ -209,13 +228,61 @@ export default {
...
+                !this.parentEntity?.id &&
+                !!this.entity?.id &&
+                typeof this.entity?.getEntityName === 'function' &&
+                !!this.translatedInheritanceLanguageId
+            );
+        },
 
-            if (value) {
-                return value;
+        hasOverriddenTranslatedCustomFields() {
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:255]: Name can be simplified to: `hasOwnOverrides`.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 5]
```diff
@@ -102,16 +102,18 @@ export default {
...
             refreshVisibleSets: false,
+            translatedInheritanceLoadKey: null,
         };
     },
 
     computed: {
         hasParent() {
-            return this.parentEntity ? !!this.parentEntity.id : false;
+            return !!this.parentEntity?.id || this.isTranslatedCustomFieldInheritanceContext();
         },
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:130]: Suggestion on how to make the intent clearer:

```suggestion
        hasParent() {
            return this.hasExplicitParentEntity || this.usesTranslatedInheritance;
        },
    
        hasExplicitParentEntity() {
            return !!this.parentEntity?.id;
        },
```

_**this.isTranslatedCustomFieldInheritanceContext()** got renamed to **this.usesTranslatedInheritance**_

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 6]
```diff
@@ -209,13 +228,61 @@ export default {
...
 
-        getInheritedCustomField(customFieldName) {
-            const value = this.parentEntity?.translated?.customFields?.[customFieldName] ?? null;
+        isTranslatedCustomFieldInheritanceContext() {
+            return (
+                !this.parentEntity?.id &&
+                !!this.entity?.id &&
+                typeof this.entity?.getEntityName === 'function' &&
+                !!this.translatedInheritanceLanguageId
+            );
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Instead of using too many `!!`, use the explicit boolean conversion.
```suggestion
            return Boolean(
                !this.parentEntity?.id &&
                this.entity?.id &&
                typeof this.entity?.getEntityName === 'function' &&
                this.translatedInheritanceLanguageId
            );
```

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:412]: Because we are at it, refactor this function

```suggestion
return this.sets
    .flatMap((set) => set.customFields)
    .find((customField) => customField.name === customFieldName);
},
```

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 7]
```diff
@@ -102,16 +102,18 @@ export default {
     data() {
         return {
             customFields: {},
+            inheritedCustomFields: null,
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: This property only represents the indirect (translated) inheritance
```suggestion
            indirectInheritedCustomFields: null,
```

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 8]
```diff
@@ -209,13 +228,61 @@ export default {
...
+        },
+
+        getTranslatedInheritanceContext() {
+            return {
+                ...Shopware.Context.api,
+                languageId: this.translatedInheritanceLanguageId,
+            };
+        },
+
+        isInheritedTranslatedCustomField(customFieldName) {
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:293]: Suggestion: simplify the name, since the context about custom fields is clear

```suggestion
        isOverwritten(customFieldName) {
```

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 9]
```diff
@@ -209,13 +228,61 @@ export default {
...
+            return this.customFields?.[customFieldName] === null || this.customFields?.[customFieldName] === undefined;
+        },
+
+        getInheritedCustomFields(customFieldName) {
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:297]: What is the intent of this method?
It gives me a whole set of custom fields. But why should I provide a customFieldName then?
If it is about that exact field, give that out directly: `returnedCustomFields?.[customFieldName]`

**Review by gweiermann — CHANGES_REQUESTED** [review]
The method names should be improved for better readability, clearly describing their immediate intent. It took me quite a long time to really understand each method.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Not relevant anymore

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 4 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:255]: I think this is too generic. It loses the important connection to "translatedCustomFields"

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 6 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: I am not sure if this is really more readable 🤔 I would keep it like before if there is no specific benefit instead of style preference

Comment (gweiermann) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: The benefit is that you see a lot of `!` and you start counting them. With Boolean, you get the same logic but more readable because only one `!` exists for negation instead of converting a value to a Boolean.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 2 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Renamed this to `translatedInheritanceSourceLanguageId` since it can also resolve to the system-language fallback, not only the parent language.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 7 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Renamed this state to `indirectInheritedCustomFields` so it matches the translated/indirect inheritance it actually stores.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 9 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:297]: Adjusted `getInheritedCustomFields(customFieldName)` to return the requested field value directly and added focused regression coverage for it.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 3 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Renamed this to `isTranslatedCustomFieldFallbackContext()` to make the fallback semantics clearer while keeping the scope small.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 5 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:130]: Split this into `hasExplicitParentEntity` and `usesTranslatedInheritance`, and kept `hasParent` as the composed flag.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 3 above)
Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js]: Final version uses `usesTranslatedInheritance` after splitting the explicit parent case out separately, so the fallback/inheritance intent is shorter and clearer now.

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js (hunk 4 above)
Comment (gweiermann) [reply src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:255]: ~But it only focuses on the local custom fields without looking at the parent entity or the translated inheritance situation. Why do we need to mention them?~

Edit: my bad. `customFields` comes from `this.entity`
It's really difficult to track down each property and its meaning. Maybe we should add doc comments for each property and data?

File: src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js [hunk 10]
```diff
@@ -269,17 +298,18 @@ export default {
             const parentCustomFields = this.parentEntity?.translated?.customFields;
 
             if (parentCustomFields) {
-                return parentCustomFields;
+                return parentCustomFields?.[customFieldName];
+            }
+
+            if (!this.usesTranslatedInheritance || !this.isInheritedTranslatedCustomField(customFieldName)) {
+                return this.indirectInheritedCustomFields?.[customFieldName];
             }
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/app/component/form/sw-custom-field-set-renderer/index.js:312]: What is this checking?
In my own words, I would sum it up as:
"If we have neither the language inheritance nor something overwritten, then return the language inheritance fields."
Feels contradictory.

In other words:
If `!this.usesTranslatedInheritance` is true, `loadInheritedCustomFields` won't set `indirectInheritedCustomFields` in the first place.

**Review by gweiermann — APPROVED** [review]

**Comment by jleifeld** [comment]
Fixes https://github.com/shopware/shopware/issues/8498
