### PR TITLE
fix: prevent overencoding external urls and control character filtering

### LINKED ISSUE #15357: External images containing non-ASCII charaters are not displayed on the product page
### Shopware Version

6.7.5.1

### Affected area / extension

Platform(Default)

### Actual behaviour

Image medias created via an external link (using the `/_action/media/external-link` endpoint) are not displayed on the product page if the URL contains umlauts—even when the URL is correctly URI-encoded. In the administration interface, however, these media files are displayed correctly.

On the product page, the URL—already URI-encoded when the media is created—is encoded a second time, resulting in an invalid URL.
If the URL is not URI-encoded before creation, the umlauts are removed entirely, which is also incorrect.

### Expected behaviour

The image gets loaded correctly on the product page.

### How to reproduce

1. Create a new image media using the `/_action/media/external-link` endpoint with a URL that contains umlauts but is correctly URI-encoded (e.g., https://example.net/Geschenkt%C3%BCte.jpg, where ü is encoded).
2. Attach the media to a product (the image loads correctly in the administration interface).
3. Open the product page for that product.

The image is not loaded because the URL is encoded a second time (e.g. https://example.net/Geschenkt%25C3%25BCte.jpg) on the product page, which makes the URL invalid.

### PR DESCRIPTION
**Pull request by dneustadt**
### 1. Why is this change necessary?
* Media pointing to an external URL that was created using an URL that includes encoded Characters get re-encoded (overencoded) in the Storefront without the URL having been decoded before.
* With external URLs that weren't encoded but included for example umlauts (ä, ü, ö), the filtering for non-printable characters is too aggressive and removed the umlauts aus well.

The combination of these two issues essentially prevented use of external URL media that includes characters like umlauts.

### 2. What does this change do, exactly?
* URL-decode any URL used with `/api/_action/media/external-link` to create media from. Only store decoded paths so they may safely be encoded in the Storefront again.
* Loosen the regex to not so aggressively strip characters in paths but instead only strip control characters or invisible formatting characters.

### 3. Describe each step to reproduce the issue or behaviour.
* Upload media using `/api/_action/media/external-link` with a URL that includes encoded or unencoded umlauts.
* Assign that media to a product
   * If URL was encoded: Media-URL in the storefront will be "double" URL encoded
   * If URL was NOT encoded: Media-URL in the storefront will lack the umlauts

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Content/Media/Subscriber/MediaCreationSubscriber.php [hunk 1]
```diff
@@ -37,7 +37,8 @@ public function beforeWrite(EntityWriteEvent $event): void
     private function filterFilePath(array $commands): void
     {
         foreach ($commands as $command) {
-            $path = preg_replace('/[\x00-\x1F\x7F-\xFF]/', '', $command->getPayload()['path']);
```
Comment (vienthuong) [inline src/Core/Content/Media/Subscriber/MediaCreationSubscriber.php:40]: There is a few places in \Shopware\Core\Content\Media\Api\MediaUploadController that we are still using this preg_replace with this regex, do we need to update there as well?

Comment (mitelg) [reply src/Core/Content/Media/Subscriber/MediaCreationSubscriber.php:40]: if so, we should put that regex into a constant and re-use it everywhere

Comment (mitelg) [reply src/Core/Content/Media/Subscriber/MediaCreationSubscriber.php:40]: I found nine places of this regex all over the src code

**Review by marcelbrode — APPROVED** [review]

**Review by vienthuong — APPROVED** [review]

File: src/Core/Defaults.php [hunk 2]
```diff
@@ -40,4 +40,8 @@ final class Defaults
     public const STORAGE_DATE_FORMAT = 'Y-m-d';
 
     public const CMS_PRODUCT_DETAIL_PAGE = '7a6d253a67204037966f42b0119704d5';
+
+    public const PATH_SANITIZE_REGEX = '/[\x00-\x1F\x7F\p{Cf}]/u';
```
Comment (mitelg) [inline src/Core/Defaults.php]: imo, we should not add this to this class. 

as this is very domain specific, it should go somewhere into `Content`, wdyt?

File: src/Core/Content/Media/Subscriber/MediaCreationSubscriber.php (hunk 1 above)
Comment (dneustadt) [reply src/Core/Content/Media/Subscriber/MediaCreationSubscriber.php:40]: fyi in some cases stripping down to ascii was a requirement, in particular when used as a fallback name in disposition headers, so I kept usage of the former regex in these cases.

File: src/Core/Defaults.php (hunk 2 above)
Comment (dneustadt) [reply src/Core/Defaults.php]: I see, I added a classic helper class for general use in context of media paths.

File: src/Core/Content/Media/Util/PathHelper.php [hunk 3]
```diff
@@ -0,0 +1,19 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\Content\Media\Util;
+
+use Shopware\Core\Framework\Log\Package;
+
+#[Package('discovery')]
+class PathHelper
+{
+    public static function stripControlAndFormatChars(string $path, string $replace = ''): ?string
```
Comment (mitelg) [inline src/Core/Content/Media/Util/PathHelper.php]: as `null` is an error case, we should return string only and cover the `null` with throwing an exception to make clear, that there was an error. wdyt?

File: src/Core/Content/Media/Util/PathHelper.php [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+    {
+        return preg_replace('/[\x00-\x1F\x7F\p{Cf}]/u', $replace, $path);
```
Comment (mitelg) [inline src/Core/Content/Media/Util/PathHelper.php]: as those regexes are very cryptic, we should introduce private constants with descriptive names

File: src/Core/Content/Media/Util/PathHelper.php (hunk 3 above)
Comment (dneustadt) [reply src/Core/Content/Media/Util/PathHelper.php]: In theory, yes. However, in reality this could be considered a breaking change as it stands, as null cases are actually handled. See:
```php
            $path = PathHelper::stripControlAndFormatChars($command->getPayload()['path']);

            $command->addPayload('path', \is_string($path) ? $path : null);
```

```php
        $disposition = HeaderUtils::makeDisposition(
            $forceDownload ? HeaderUtils::DISPOSITION_ATTACHMENT : HeaderUtils::DISPOSITION_INLINE,
            $filename,
            // only printable ascii
            PathHelper::stripNonAsciiAndControlChars($filename, '_') ?? ''
        );
```

I introduced both the Helper's methods with a return type deprecation and warning... does that seem ok to you?

File: src/Core/Content/Media/Util/PathHelper.php (hunk 4 above)
Comment (dneustadt) [reply src/Core/Content/Media/Util/PathHelper.php]: ✅

File: src/Core/Content/Media/Util/PathHelper.php (hunk 3 above)
Comment (mitelg) [reply src/Core/Content/Media/Util/PathHelper.php]: why not throwing an exception and handle them on caller side in the same way `null` values are now handled?

File: src/Core/Content/Media/Util/PathHelper.php [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+    private const REGEX_CONTROL_AND_INVISIBLE_FORMAT_CHARACTERS = '/[\x00-\x1F\x7F\p{Cf}]/u';
+
+    private const REGEX_NON_ASCII_AND_CONTROL_BYTE_RANGES = '/[\x00-\x1F\x7F-\xFF]/';
+
+    public static function stripControlAndFormatChars(string $path, string $replace = ''): string
+    {
+        $stripped = preg_replace(self::REGEX_CONTROL_AND_INVISIBLE_FORMAT_CHARACTERS, $replace, $path);
+
+        if ($stripped === null) {
+            throw MediaException::illegalFileName($path, 'Filename must be a string');
```
Comment (mitelg) [inline src/Core/Content/Media/Util/PathHelper.php]: as we are catching those, we should introduce a dedicated exception class for the `illegalFileName`. 
just introduce a new class extending from `MediaException and return that in the `illegalFileName`. where you now catch the `MediaException`, replace with the new class

Comment (dneustadt) [reply src/Core/Content/Media/Util/PathHelper.php]: ✅

File: src/Core/Content/Media/Util/PathHelper.php (hunk 3 above)
Comment (dneustadt) [reply src/Core/Content/Media/Util/PathHelper.php]: ✅

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
very nice!
