### PR TITLE
fix: duplicate revocation request CMS form translations

### LINKED ISSUE #15584: Migration1768545320RevocationRequestCmsForm causes duplicate entry if de-DE or en-GB is missing
### Shopware Version

6.6.10.15

### Affected area / extension

Platform(Default)

### Actual behaviour

The migration Migration1768545320RevocationRequestCmsForm assumes that both de-DE and en-GB languages exist in the system. If either language is not installed, the method getLanguageIdByLocale() defaults to Uuid::fromHexToBytes(Defaults::LANGUAGE_SYSTEM) for the missing language.

This results in the same UUID being used for multiple translations, causing a database integrity violation.

### Expected behaviour

The migration should either:

- Skip the missing language without using the system language UUID for multiple entries, or
- Ensure unique translation entries even if a language is missing.

### How to reproduce

1. Remove de-DE or en-GB language from the system (or start with a fresh installation that does not include them).
3. Run the migration Migration1768545320RevocationRequestCmsForm.
5. Observe the error due to duplicate IDs when inserting into cms_page_translation or cms_slot_translation.

### PR DESCRIPTION
**Pull request by DennisGarding**
closes: #15584

Prevents Migration from inserting duplicate CMS page and slot translations when the en-GB fallback resolves to the system language and de-DE uses the same language ID.

### CODE REVIEW

File: src/Core/Migration/V6_7/Migration1768545320RevocationRequestCmsForm.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ private function createCmsPage(Connection $connection, ?string $enLanguageByteId
             );
         }
 
-        if ($deLanguageByteId !== null) {
+        if ($deLanguageByteId !== null && $deLanguageByteId !== $enLanguageByteId) {
```
Comment (larskemper) [inline src/Core/Migration/V6_7/Migration1768545320RevocationRequestCmsForm.php:73]: can we test that?

Comment (DennisGarding) [reply src/Core/Migration/V6_7/Migration1768545320RevocationRequestCmsForm.php:73]: yes, i can do write a test

**Review by MalteJanz — APPROVED** [review]

**Review by larskemper — APPROVED** [review]
