### PR TITLE
fix: a11y of plain text line item tables in mails

### LINKED ISSUE #7208: A11y: Use of spaces for table layout
*PHP Version:* 8.2   | *Shopware Version:* 6.6.9.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

The plain text version contains spaces and tab stops, which are used to organise the ordered products as a table.

Screen readers read out the email sequentially, i.e. each word is read out in sequence as it appears in the text. Plain text does not offer the option of semantically labelling content as a table. Screen readers are therefore unable to establish the link between the table cell and the corresponding table header.

When output via a Braille display, all the superfluous spaces are also output. This makes reading very difficult.

Image

*_Expected behaviour:_*

Avoid the visual representation as a table.

Check the plain text version while you are writing. For example, you can read the text to a colleague and check how well the content is conveyed.

The text could, for example, behave more like a list.
```text
Pos 1, 9783453xxx, Katalog Grundschule 2024/2025, Menge 1, Preis 18,99 €.
```
or
```text
Pos 1
-------------------
9783453xxx
Katalog Grundschule 2024/2025
Menge 1
Preis 18,99 €

### Pos 2
-------------------
...
```

*_How to reproduce:_*

- Enable `ACCESSIBILITY_TWEAKS` Feature-Flag
- Login into the shopware administration backend
- Send a test mail via the shopware mail templates module

### PR DESCRIPTION
**Pull request by MalteJanz**
closes #7208

Before:
image

After:
image

## Additional changes
Adjusted all default templates containing line items to be basically the same template except the first paragraph. These include:
- order_confirmation_mail
- order_transaction.state.paid
- order_transaction.state.cancelled

## Tips for easier code review
consider enabling this option, but keep in mind that whitespace matters for plain text emails.
image

### CODE REVIEW

File: tests/migration/Core/V6_7/Migration1748326970UpdateMailTemplatesForAccessibilityTest.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    public function testMigrationOfUnmodifiedTranslation(): void
+    {
+        $migration = new Migration1748326970UpdateMailTemplatesForAccessibility();
+        $migration->update($this->connection);
+        $migration->update($this->connection);
+
+        // at least check that the migrations run without exceptions
+
+        // there isn't much purpose in comparing the fixture contents with the DB,
+        // because future migrations might change them again, so let's skip all that boilerplate here
```
Comment (MalteJanz) [inline tests/migration/Core/V6_7/Migration1748326970UpdateMailTemplatesForAccessibilityTest.php:38]: What do you guys think about this? The Migration is not doing anything special except calling the `UpdateMailTrait` and "uploads" the fixture template files to the DB.

In general I think there is a lot of potential to refactor our email template system to be:
- easier to maintain
- less error prone for users

but that is a different topic 😅

Comment (jozsefdamokos) [reply tests/migration/Core/V6_7/Migration1748326970UpdateMailTemplatesForAccessibilityTest.php:38]: I see other migrations of this type dont even have test files. I dont see much point of having it here either. As you say it only calls to an external trait.

**Review by jozsefdamokos — APPROVED** [review]

**Review by GitEvil — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]
