### PR TITLE
fix: use the billing address country for the vat id validation

### LINKED ISSUE #13788: Registration form validates VAT ID of the shipping address instead of the billing address
### Shopware Version

6.7.4.2

### Affected area / extension

Platform(Default)

### Actual behaviour

When a new business customer registers on a Shopware shop with active VAT ID Validation for the specified countries, they will not be able to register if the shipping address is in a different country than their VAT ID.

Example: Customer in Sweden wants to specify a shipping address in Slovenia. Both countries have VAT ID validation enabled. In the registration form, the Swedish VAT ID (example: `SE999999999901`) should be validated, however instead the Slovenian VAT ID (example: `SI12345678 `) is being validated:

Image

Workaround: first register without a shipping address, then add it later in the account. The VAT ID will not be validated at that point.

### Expected behaviour

The VAT ID of the billing address is being validated

### How to reproduce

- Set two countries to validate the VAT ID under Settings > Countries
- Enable the option to register as business customer
- Try to register a business with a shipping address in a different country

### PR DESCRIPTION
**Pull request by dgrothaus-sw**
When the shipping address mismatches the billing address, don't use the country of the shipping address to validate the VAT ID of the billing address.

### 1. Why is this change necessary?

When creating a business account and having a shipping address different from the billing address, the VAT ID is being validated against the country of the shipping address although belonging to the billing address.

### 2. What does this change do, exactly?

It changes the country used to validate the VAT ID from the shipping address to the billing address.

### 3. Describe each step to reproduce the issue or behaviour.

1. Enable business registrations
2. Enabled VAT validation for two countries having a VAT ID validation pattern A and B.
3. Register as a new business. Have the billing address set to country A, enter a shipping address of country B.
4. Enter a valid VAT ID for country A
5. Try to submit the form

### 4. Please link to the relevant issues (if any).

Fixes https://github.com/shopware/shopware/issues/13788

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php [hunk 1]
```diff
@@ -377,9 +377,9 @@ private function validateRegistrationData(
         }
 
         if ($accountType === CustomerEntity::ACCOUNT_TYPE_BUSINESS) {
-            $countryId = $shippingAddress instanceof DataBag
-                ? $shippingAddress->get('countryId')
-                : ($billingAddress instanceof DataBag ? $billingAddress->get('countryId') : null);
+            $countryId = $billingAddress instanceof DataBag
```
Comment (mitelg) [inline src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php:380]: should be clarified with legal, when which address needs to be considered

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by MartinKrzykawski — COMMENTED** [review]
LGTO, i will give an approval if the open comment is clarified :)

**Comment by dgrothaus-sw** [comment]
@mitelg Finance seems to have no objections on the change. But the answers are quite _financy_.
Another thing that I tested. If, without the change, you create a business account with just a billing address, you can then just add a shipping address in the account settings without this validation. Any address added via account settings can be chosen and used as default shipping address. To me the check in the registration seems even more like an error, or the check was missed in the account settings. What do you think?

**Comment by mitelg** [comment]
@dgrothaus-sw sorry for the late answer, this somehow slipped through :face_with_peeking_eye: 

if an account has only one address it must be for sure valid also for shipping. and that would mean having a vat ID. once they differ, afaik and imo only the shipping address needs to be valid :thinking: 
So I would say the validation must take place once one address is considered for shipping. during registration, but also if a new address is created and/or set as shipping address.

**Comment by dgrothaus-sw** [comment]
@mitelg Sorry for being late as well.

I think I wasn't exactly precise with my wording. The addresses are validated when added later. It's just that this specific check is not done for later added addresses. So when creating the account, the VAT ID of the base address is checked against the country of the shipping address. Whereas when adding an address later, the VAT ID of the added (shipping) address is validated against the country of the added (shipping) address.

With this change, the behaviour will be consistent.

**Comment by dgrothaus-sw** [comment]
Results of the internal discussions with finance and the lead during the original implementation:

A VAT ID belongs to the **company**, not to any address. A company can have multiple VAT IDs — that is also why the field was moved off the address entity in the first place. It makes no sense to validate it against a shipping address, which could be anything (a construction site, a warehouse, a third-party location) and has no legal connection to where the company is registered.

The **billing address** is the correct basis for validation, as it can safely be assumed to reflect the company's country of residence/registration.

This was already broken with the previous change: https://github.com/shopware/shopware/commit/828fe3893a6e788b0c0ad84460b6ab6787d7f5ea This PR fixes it.

Before changing this again, please check:
- Confluence: [Umsatzsteuer-ID Handling](https://shopware.atlassian.net/wiki/spaces/CORE/pages/18811492293/Umsatzsteuer-ID+Handling)
- Jira: [NEXT-37997](https://shopware.atlassian.net/browse/NEXT-37997)
- EU page about taxation: https://taxation-customs.ec.europa.eu/taxation/vat/vat-directive/place-taxation_en

Here are other examples of the assumption, that an address can have a VAT ID:
- [VAT ID of guest accounts can't be changed via the shipping address. ](https://feedback.shopware.com/forums/942607-shopware-6-product-feedback-ideas/suggestions/49790531-vat-id-of-guest-accounts-can-t-be-changed-via-the)
- https://github.com/shopware/shopware/issues/4249

The Dutch/Belgian/Spanish example taken from the [EU page about taxation[(https://taxation-customs.ec.europa.eu/taxation/vat/vat-directive/place-taxation_en) makes clear, that the Dutch buyer is using a Dutch VAT ID for products purchased in Belgium, shipped to Spain.

[NEXT-37997]: https://shopware.atlassian.net/browse/NEXT-37997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by mitelg — APPROVED** [review]

**Review by MartinKrzykawski — APPROVED** [review]
