### PR TITLE
fix(framework): avoid double slash in plugin class path

### LINKED ISSUE #11959: Double slash in Plugin->path
### Shopware Version

6.7.1.2

### Affected area / extension

Platform(Default)

### Actual behaviour

When installing a plugin via composer the Symfony bundle path includes a double slash.

https://github.com/shopware/shopware/blob/0e363a95fc487b7e1b4c3689c261e8e0c9b22a9a/src/Core/Framework/Plugin.php#L21-L31

At line 23 the `basePath` ends with a `/`. On line 30 `computePluginClassPath` is called:

https://github.com/shopware/shopware/blob/0e363a95fc487b7e1b4c3689c261e8e0c9b22a9a/src/Core/Framework/Plugin.php#L128-L140

On line 136 the line the statement `$this->basePath . $relativePluginClassPath;` concatenates the 2 paths, but `$relativePluginClassPath` includes a leading slash, so we have a double slash:
`/base/path//plugin/path`

### Expected behaviour

The plugin path should only contain single slashes.

I think the solution is to strip the trailing slash of the base path at the beginning of the constructor via `$this->basePath = rtrim($this->basePath, '/');`.

### How to reproduce

- Install a plugin via composer, e.g. follow https://github.com/FriendsOfShopware/FroshDevelopmentHelper?tab=readme-ov-file#installation
- Set a breakpoint at L30 and a breakpoint at L136 and see that we get a trailing and a leading slash.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mvanhorn**
### 1. Why is this change necessary?

Closes #11959. When a plugin is installed via composer, the Symfony bundle path can contain a double slash like `/base/path//plugin/path`. This breaks tooling that compares paths verbatim or walks the filesystem with strict path normalisation, because the bundle path no longer matches the canonical one.

### 2. What does this change do, exactly?

In `src/Core/Framework/Plugin.php` `computePluginClassPath()`, the concatenation `$this->basePath . $relativePluginClassPath` is now `rtrim($this->basePath, '/') . $relativePluginClassPath`.

Root cause (from the issue author's analysis):
- The constructor may leave `$this->basePath` ending with a trailing slash (e.g. `/base/path/`).
- `$relativePluginClassPath` is computed as `mb_substr($canonicalizedPluginClassPath, mb_strlen($canonicalizedPluginPath))`, where `$canonicalizedPluginPath` comes from `realpath()` (which strips trailing slashes). So `$relativePluginClassPath` always starts with a `/`.
- Concatenating a trailing-slash basePath with a leading-slash relative path produces the double slash.

I kept the fix confined to the concatenation site rather than normalising `$this->basePath` in the constructor. That way `getBasePath()` returns the exact value it does today and no external consumer of that method is affected. `rtrim('/foo', '/')` on a path without a trailing slash is a no-op, so paths without the trailing slash still concatenate identically.

### 3. Describe each step to reproduce the issue or behaviour.

1. Install a plugin via composer such that the base path ends with `/` (as reported in the issue).
2. Inspect the Symfony bundle path via `$plugin->getPath()`.
3. Before: path contains `//` (e.g. `/base/path//plugin/path`).
4. After: path contains single slashes only (e.g. `/base/path/plugin/path`).

### 4. Please link to the relevant issues (if any).

- closes #11959

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change — **not added**: the existing `PluginTest` uses real filesystem fixtures via `__DIR__` which don't reproduce the trailing-slash case; a synthetic regression test would require mocking the filesystem. Happy to add one if the maintainer prefers a specific approach.
- [x] I have updated developer-facing release notes if this change is relevant for external developers — this is a fix, not a behaviour change for external developers (`getBasePath()` return value is unchanged). No RELEASE_INFO or UPGRADE entry needed.
- [x] I have written or adjusted the documentation according to my changes — N/A, internal path handling only.
- [x] This change has comments for package types, values, functions, and non-obvious lines of code — the `rtrim` call is a drop-in normaliser; no added comments needed.
- [x] I have read the contribution requirements and fulfilled them.

Closes #11959

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

File: src/Core/Framework/Plugin.php [hunk 1]
```diff
@@ -125,7 +125,7 @@ private function computePluginClassPath(): string
         if ($canonicalizedPluginPath !== false && mb_strpos($canonicalizedPluginClassPath, $canonicalizedPluginPath) === 0) {
             $relativePluginClassPath = mb_substr($canonicalizedPluginClassPath, mb_strlen($canonicalizedPluginPath));
 
-            return $this->basePath . $relativePluginClassPath;
+            return rtrim($this->basePath, '/') . $relativePluginClassPath;
```
Comment (mitelg) [inline src/Core/Framework/Plugin.php]: what about using `\Symfony\Component\Filesystem\Path::join` instead?

**Review by mitelg — CHANGES_REQUESTED** [review]
would be nice, if you could also write a test for this case

**Comment by mvanhorn** [comment]
Thanks @mitelg, addressed in 2b6c942d:

- Swapped `rtrim + concat` for `Symfony\Component\Filesystem\Path::join($this->basePath, $relativePluginClassPath)`. Consistent with the existing Path::join usage across `src/Core/Framework` (AppExtractor, RemoteZip, TemporaryDirectoryFactory, StaticFilesystem, Filesystem).
- Added `testGetPathWithTrailingSlashBasePath` in `tests/unit/Core/Framework/Plugin/PluginTest.php` covering the original bug: trailing slash on basePath must not produce `//` in the returned class path.

No PHP toolchain locally so I'm relying on CI for the test run.

File: src/Core/Framework/Plugin.php (hunk 1 above)
Comment (mvanhorn) [reply src/Core/Framework/Plugin.php]: Done in 2b6c942d - swapped the rtrim+concat for Path::join.

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
@mvanhorn thanks, much better now. but some tests relied on non-canonical path :sweat_smile: would be nice if you could fix that

**Comment by mvanhorn** [comment]
CI flagged the existing testGetPathWithNonSymlinkedPlugin too - Path::join lexically normalizes the test fixture path (resolves the `__DIR__/../../...` segments and removes the duplicate slash), so the original assertion no longer round-trips. realpath()'d swagTestPluginPath once in setUpBeforeClass so all tests see the canonical fixture path (24d46fa3). Production composer-installed plugin paths don't carry `..` segments, so this is test-only.

File: tests/unit/Core/Framework/Plugin/PluginTest.php [hunk 2]
```diff
@@ -19,7 +19,11 @@ class PluginTest extends TestCase
     public static function setUpBeforeClass(): void
     {
         $pluginsDir = __DIR__ . '/../../../../../src/Core/Framework/Test/Plugin/_fixture/plugins/';
-        self::$swagTestPluginPath = $pluginsDir . '/SwagTestPlugin';
+        $swagTestPluginPath = realpath($pluginsDir . '/SwagTestPlugin');
+        if ($swagTestPluginPath === false) {
+            throw new \RuntimeException('SwagTestPlugin fixture directory must exist');
+        }
```
Comment (mitelg) [inline tests/unit/Core/Framework/Plugin/PluginTest.php]:
```suggestion
        static::assertIsString($swagTestPluginPath);
```

**Review by mitelg — APPROVED** [review]

**Review by BrocksiNet — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @mvanhorn 👍🎉💙

**Comment by mvanhorn** [comment]
Thanks for landing the double-slash fix, @mitelg.
