### PR TITLE
NEXT-8435 Test for duplicate script entrypoints

### LINKED ISSUE #486: NEXT-8435 - theme:dump outputs duplicates
**Description**  
I have installed some plugins and the hot proxy is not working any more. I traced down the cause and found that the generated `var/theme-files.json` which contains the entrypoints for webpack contains the plugin entrypoints more than once:

```json
{
    "script": [
        {
            "filepath": "\/app\/vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/main.js",
            "resolveMapping": [],
            "extensions": []
        },
        {
            "filepath": "\/app\/vendor\/store.shopware.com\/swagenterprisesearchplatform\/src\/Resources\/app\/storefront\/src\/main.js",
            "resolveMapping": [],
            "extensions": []
        },
        {
            "filepath": "\/app\/vendor\/store.shopware.com\/swagcmsextensions\/src\/Resources\/app\/storefront\/src\/main.js",
            "resolveMapping": [],
            "extensions": []
        },
        {
            "filepath": "\/app\/vendor\/store.shopware.com\/swagenterprisesearchplatform\/src\/Resources\/app\/storefront\/src\/main.js",
            "resolveMapping": [],
            "extensions": []
        }
    ],
```

This causes webpack to fail with:

```
(node:1338) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
         - configuration.entry['storefront'] should not contain the item '/app/vendor/store.shopware.com/swagcmsextensions/src/Resources/app/storefront/src/main.js' twice.
           -> A non-empty array of non-empty strings
```

The recursive call of `resolve` in the `ThemeFileResolver` is called with the following stack:

```
@Storefront
     vendor/shopware/storefront/Resources/app/storefront/src/main.js
     @Plugins
@Plugins
```

Therefore the plugins are resolved twice and added as duplicates.

### PR DESCRIPTION
**Pull request by htuscher**
### 1. Why is this change necessary?

#486

### 2. What does this change do, exactly?

The `ThemeFileResolver` works recursively and replaces placeholders like `@Plugins` with the actual plugins. If you inherit from `@Storefront`, it brings an additional `@Plugins` which is also resolved.

As you can only have on theme active at the same time, it's up to that theme to decide on the inheritance chain. (As discussed with @tobiasberge and @xPand4B )

Therefore we track the recursion level of the resolver and let the `@Plugins` placeholder only resolve on top level.

### 3. Describe each step to reproduce the issue or behavior.

1. You build a theme with `bin/console theme:create MyTheme`.
2. Install and activate the theme
3. Modify the `theme.json` so it contains `@Plugins` as `script` entrypoint e.g.
4. Run `bin/console theme:dump` 

You will notice that you have duplicates in the `var/theme-files.json` file.

### 4. Please link to the relevant issues (if any).

#486

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by mitelg** [comment]
please remember to fill out the PR template :blush:

File: src/Storefront/Test/Theme/ThemeFileResolverTest.php [hunk 1]
```diff
@@ -61,4 +64,36 @@ public function testResolvedFilesDoNotIncludeSkinScssPath(): void
 
         static::assertStringNotContainsString($notExpected, $actual);
     }
+
+    /**
+     * NEXT-8435
```
Comment (mitelg) [inline src/Storefront/Test/Theme/ThemeFileResolverTest.php]: we do not add ticket numbers in tests :blush:

**Comment by leichteckig** [comment]
QA approved :heavy_check_mark:

**Comment by xPand4B** [comment]
Thanks for your contribution @hhoechtl :+1:
