### PR TITLE
fix: document bulk download

### LINKED ISSUE #15710: The ZUGFeRD e-invoice cannot be downloaded using the bulk edit function
### Shopware Version

6.7.8.1

### Affected area / extension

Platform(Default)

### Actual behaviour

ZUGFeRD e-invoices and PDFs containing embedded ZUGFeRD e-invoices cannot be downloaded via the bulk edit function.  
When you start the bulk edit, a window opens, but nothing happens and nothing is displayed.

### Expected behaviour

The selected documents will be downloaded, just as they would be with a regular invoice.

### How to reproduce

Generate an e-invoice for an order, then try to download it using bulk edit.

### PR DESCRIPTION
**Pull request by DennisGarding**
closes: #15710 

Preserves original file metadata for single downloads and falls back to ZIP for mixed or non-PDF bulk downloads. Also ensures regenerated documents use the configured file type.

### CODE REVIEW

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 1]
```diff
@@ -128,16 +158,16 @@ private function mergeWithFpdi(DocumentCollection $documents, Context $context,
         return $renderedDocument;
     }
 
-    private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Context $context): ?string
+    private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Context $context): ?DocumentEntity
```
Comment (larskemper) [inline src/Core/Checkout/Document/Service/DocumentMerger.php:161]:
```suggestion
    private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Context $context): DocumentEntity
```

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 2]
```diff
@@ -165,7 +195,7 @@ private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Cont
         $document = $this->documentRepository->search($criteria, $context)->getEntities()->first();
         \assert($document !== null);
```
Comment (larskemper) [inline src/Core/Checkout/Document/Service/DocumentMerger.php:196]: i know you did not add this, but a proper exception for this case would be good.

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 3]
```diff
@@ -74,18 +71,51 @@ public function merge(array $documentIds, Context $context): ?RenderedDocument
...
+            name: $fileName . '.' . $fileExtension,
+            fileExtension: $fileExtension,
+            contentType: $contentType,
+        );
+        $renderedDocument->setContent($fileBlob);
+
+        return $renderedDocument;
+    }
+
+    private function containsOnlyPdfs(DocumentCollection $documents): bool
```
Comment (larskemper) [inline src/Core/Checkout/Document/Service/DocumentMerger.php:108]: a test for "all pdf, multi doc, no zip" would be good. So we check regression

**Review by larskemper — APPROVED** [review]

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 1 above)
Comment (DennisGarding) [reply src/Core/Checkout/Document/Service/DocumentMerger.php:161]: ?  if there is no document type or document struct, we return null

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 2 above)
Comment (DennisGarding) [reply src/Core/Checkout/Document/Service/DocumentMerger.php:196]: this is just in dev mode. In Prod, we return null here. This should be fine

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 3 above)
Comment (DennisGarding) [reply src/Core/Checkout/Document/Service/DocumentMerger.php:108]: already catched in \Shopware\Tests\Integration\Core\Checkout\Document\Service\DocumentMergerTest::testMerge

**Review by larskemper — APPROVED** [review]

**Review by jozsefdamokos — APPROVED** [review]
