### PR TITLE
fix: Selection of document types

### LINKED ISSUE #7997: Document file format is not selectable
### PHP Version

8.3

### Shopware Version

6.6.x

### Affected area / extension

Platform(Default)

### Actual behaviour

If the ACCESSABILITY_TWEAK is enabled, the feature file formats are available for document templates (invoices). Currently, the merchant cannot select the file format from the select list (PDF or HTML)

Image

### Expected behaviour

The file formats for invoices should be selectable and visible in the input box.

### How to reproduce

1. ACCESSABILITY_TWEAK feature flag is enabled
2. Create a new Document template via settings > documents 
3. Try to select file format PDF or HTML from the selection list

### PR DESCRIPTION
**Pull request by DennisGarding**
fix: #7997 
Closes #7997

### CODE REVIEW

**Comment by mitelg** [comment]
please add the GitHub issue to the description with `Closes #1234` 

also please do not add me to admin things as reviewer :sweat_smile: I am not the best person for that stuff

**Review by jozsefdamokos — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-document/page/sw-settings-document-detail/index.js [hunk 1]
```diff
@@ -630,6 +630,10 @@ export default {
         },
 
         onAddDocumentType(type) {
+            if (!this.documentConfig.config.fileTypes) {
+                this.documentConfig.config.fileTypes = [];
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-settings-document/page/sw-settings-document-detail/index.js:635]: This fix is fine for me and I would leave the additional check here (I don't know where that property gets initialized).

But why we don't initialize the property to an empty array here? Or is it important that it can be `undefined` in some cases?
https://github.com/shopware/shopware/blob/ac0882f849b288cacdf897f921e73c4e72b36ea8/src/Administration/Resources/app/administration/src/module/sw-settings-document/page/sw-settings-document-detail/index.js#L49-L53

**Review by MalteJanz — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-document/page/sw-settings-document-detail/index.js (hunk 1 above)
Comment (DennisGarding) [reply src/Administration/Resources/app/administration/src/module/sw-settings-document/page/sw-settings-document-detail/index.js:635]: Good Idea. I also add it to the initial config! :+1:
